services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 127.0.0.1:5432:5432/tcp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1" ]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  postgres-data:
